### ISSUE TITLE
Mouse cursor size borrowed from desktop resolution, not game resolution

### ISSUE THREAD

**Issue by CobraA1** [voxeltycoon/issues#1000]
**Describe the bug**
Whenever I use my 4K TV with the desktop at a high resolution, the mouse cursor appears tiny in the game. This happens even when the game is set to a low resolution or high UI scaling.

**Steps to reproduce**
On Steam Deck: Connect to a 4K TV, go to display settings and set a 4K resolution. Then launch the game.

Adjusting launch resolution and in-game settings doesn't seem to make a difference, only setting the display settings in SteamOS itself.

**Build version**
0.86.2.3

**Platform**
SteamOS (on Steam Deck) is primary use case, although I was able to reproduce the issue on Windows.

**Reproducibility**
Easy to reproduce on the Steam Deck.

**Logs/saves**
Available if requested.

**Desired behavior**

- The mouse cursor should not be tiny at low resolutions; the size should be consistent with the scaling / resolution settings.
- Would like the mouse cursor size scale with the UI scaling - if I increase the UI scale at 4K resolution, the mouse cursor should scale as well.

**Comment by andrewpey** [comment]
The cursor in the game is rendered in hardware mode. This means its rendering is controlled by OS, not the game itself.

As a workaround, we can try to add an option to enable software rendering mode, but this mode has its downsides, like, it could move not as smoothly as hardware one due to inconsistent frame rates.

**Comment by CobraA1** [comment]
If you are using custom cursors, maybe you could have two or three sizes that the game selects depending on the circumstance (or on user preference, which might be easier to implement?).

Otherwise, I would like the option of a software cursor.

Having a tiny cursor makes it really easy to lose track of it. Almost unplayable on a game that largely depends on mouse / keyboard support.

**Comment by andrewpey** [comment]
It took some time, but finally the solution is here: we've added support for software cursor rendering in the recent 
[beta](https://voxeltycoon.xyz/devlog/beta-branch/) update. It respects the UI scale so this should definitely improve things for you.

You can toggle it _Settings -> General -> Use software cursor_.
