### ISSUE TITLE
Unable to assign any keybindings with mods

### ISSUE THREAD

**Issue by hasezoey** [voxeltycoon/issues#1006]
**Describe the bug**

I am currently unable to assign anything aside from `LMB` to any button

**Steps to reproduce**

1. Open to `Settings`
2. Go to tab `Controls`
3. select a control to change
4. press buttons
5. observe nothing gets applied

**Build version**
0.87.3.4

**Platform**
Linux Manjaro KDE Wayland

**Reproducibility**
Always

**Logs/saves**

**Comment by andrewpey** [comment]
Can you share the log file generated after you trying to bind a key?

**Comment by hasezoey** [comment]
video showcasing the problem: https://www.youtube.com/watch?v=AwF6KFIuzV8 (freshly uploaded, no higher qualities available)

PS: ignore the black bars for now

**Comment by hasezoey** [comment]
I just tried again from the main menu and from a save without mods, and there it just works
so it is a mod problem, though i dont know which or why

anyway the log file (with mods): [Player.log](https://github.com/voxeltycoon/issues/files/10099097/Player.log)

**Comment by andrewpey** [comment]
Thanks for all the into. Nice to hear it is working correctly in the base game.

Unfortunately, the log doesn't show any errors, so it's hard to tell what exactly happening. If you or somebody will help us to narrow down the list of suspects to the exact mod which causes troubles, we could try to debug its behavior.

**Comment by hasezoey** [comment]
i tried narrowing it down, but after having gone through all and having accidentally set a option that prevented me from continuing, i had reset the config and since then it does not happen anymore with any mod.
btw reverting to the old config is also not broken anymore.

i have no clue what cause this or why it does not happen anymore - but it works now again, with all mods or no mods

PS: the thing that prevented me from continuing was setting `LMB` to `Enter fullscreen` and having accidentally before pushed `Hide UI`

**Comment by andrewpey** [comment]
Good to hear you've sorted it out!
