### ISSUE TITLE
Memory leak on Mac OS

### ISSUE THREAD

**Issue by vertix** [voxeltycoon/issues#1015]
**Describe the bug**
Mac OS complaining about memory after 5 mins of playing.

**Steps to reproduce**
Start new game. Play for 5 minutes (build a mine, two stations, track, depot and one train). Mac OS complains about running out of system memory. Voxel Tycoon takes ~24Gb of memory.

**Build version**
0.88.0.10

**Platform**
Mac OS 13.1 (22C65)
MacBook Pro 13-inch, M1, 2020

**Reproducibility**
Once. Wasn't able to reproduce (got into another error, https://github.com/voxeltycoon/issues/issues/1014)

**Logs/saves**
[Player-prev.log](https://github.com/voxeltycoon/issues/files/10528090/Player-prev.log)

**Comment by andrewpey** [comment]
Duplicate https://github.com/voxeltycoon/issues/discussions/924, https://github.com/voxeltycoon/issues/issues/918
