### ISSUE TITLE
Linux / Fedora 37: fail to start game -- infinite loop during loading after `exploring the world`

### ISSUE THREAD

**Issue by scienceburger** [voxeltycoon/issues#1027]
**Describe the bug**
Linux / Fedora 37: fail to start game -- infinite loop during loading after `exploring the world`

**Steps to reproduce**
1. Fedora 37 with Steam
2. Launch Voxel Tycoon and start new map 
3. Observe that game doesn't finish loading and is stuck in loop 

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
Linux Fedora 37

**Reproducibility**
0.88.2.3

**Comment by andrewpey** [comment]
[Logs](https://github.com/voxeltycoon/issues/discussions/650)?

**Comment by scienceburger** [comment]
Logs. [Player.log](https://github.com/voxeltycoon/issues/files/10826094/Player.log)

**Comment by andrewpey** [comment]
Can you try to disable Steam Overlay for VT and check if this would help?

**Comment by scienceburger** [comment]
I reinstalled Fedora (38) and the issue doesn't occur again.

**Comment by andrewpey** [comment]
Nice to hear, thank you for letting us know.
