### ISSUE TITLE
Price Change Missing on 110% UI Scaling

### ISSUE THREAD

**Issue by IDragonfire** [voxeltycoon/issues#1044]
**Describe the bug**
The price change for the last 30day is not visible:
![image](https://github.com/voxeltycoon/issues/assets/1217999/e650e1a5-a497-42d5-b777-b343fcf72e45)

**Steps to reproduce**
1. Set UI scale to 110%
2. Open any store window

**Build version**
0.88.3.1

**Platform**
* Window 10 Pro
* SteamOs 3.4.8

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Thanks for the report, fixed on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
