### ISSUE TITLE
Refitting a vehicle causes a "cash paid" sound, even though it's free

### ISSUE THREAD

**Issue by greeny** [voxeltycoon/issues#202]
When changing a vehicle's cargo type in the cog menu in depot, after clicking accept it plays the "cash paid" sound, even though you didn't lose any cash. Not a big deal, but could be a nice QOL to remove it.

**Comment by andrewpey** [comment]
The fix is live on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
