### ISSUE TITLE
Items not visible on conveyor belts

### ISSUE THREAD

**Issue by OmelchenkoA** [voxeltycoon/issues#614]
**Describe the bug**
If the endpoint of the conveyor is full after some time items will become invisible. After save/load they visible again
Screenshots made before and after save/load

![Screenshot_2](https://user-images.githubusercontent.com/48437002/115126854-d6c73b00-9fda-11eb-8672-7c2a0c6c34f2.png)
![Screenshot_2R](https://user-images.githubusercontent.com/48437002/115126852-d3cc4a80-9fda-11eb-8363-855b08d1f926.png)
![Screenshot_3](https://user-images.githubusercontent.com/48437002/115126878-0118f880-9fdb-11eb-9308-6dc0b4c4ea23.png)
![Screenshot_3R](https://user-images.githubusercontent.com/48437002/115126879-02e2bc00-9fdb-11eb-8e10-7b7af3042b1d.png)

**Steps to reproduce**
1. Fill conveyor and his endpoint
2. Play for some time. Don't know exactly when they disappear, probably when the camera is far away from them 

**Build version**
0.85.0.24 steam

**Platform**
Win10

**Reproducibility**
The issue reproduces:  often. 

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6330034/Player.log)
Save file is too big (62MB)

**Comment by andrewpey** [comment]
Should be fixed on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
