### ISSUE TITLE
Game crashes when trying to save

### ISSUE THREAD

**Issue by RobbinSchuurman** [voxeltycoon/issues#667]
**Describe the bug**
The game keeps crashing (showing bug report) when trying to save. Please find log file below:

**Steps to reproduce**
1. Load the saved game / continue the saved game from main menu
2. After loading, save the game
3. Crash / Bug report shows

**Build version**
0.85.1.0 Steam

**Platform**
Mac OS, Big Sur 11.3

**Reproducibility**
Happens continuously in the (save)game at the point where I am now. Keeps happening when loading the saved game. I didn't run into this issue before.

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/issues/files/6409003/Player.log)

**Comment by andrewpey** [comment]
Please try to disable **Double Freight Station** mod and see if this helps.
