### ISSUE TITLE
Bankruptcy Period setting does not take effect

### ISSUE THREAD

**Issue by Resugram** [voxeltycoon/issues#682]
**Describe the bug**
The business will go bankrupt even when game sets to prevent such thing from happening.
Unlike when setting is set to 3 months, a business will give notification of 190 days rather than 90 days.
Im not sure if its also a game design but once a certain resource go bankrupt, it will not show up on the same town any more.
This makes it quite have to have them let go, so disabling a bankruptcy is a sound option.

**Steps to reproduce**
1. Create new game with following difficulty:
    Bankruptcy Period: Disabled

**Build version**
v 0.85.1 (Steam)

**Platform**
Windows 10 Version 20H2 Build 19042.928

**Reproducibility**
Everytime

**Logs/saves**
Could not find steam save file.

**Images**
> ![20210502_164637](https://user-images.githubusercontent.com/29932196/116819236-152a3180-ab67-11eb-9ce7-60f3e71c6cda.png)

> ![20210502_164653](https://user-images.githubusercontent.com/29932196/116819238-165b5e80-ab67-11eb-84a9-e22553c97884.png)

**Comment by DanielBarreleiro** [comment]
If I'm not mistaken, that setting is for company (you) bankruptcy.
Not for business bankruptcy.
@RamonLiporada

**Comment by RamonLiporada** [comment]
@DanielBarreleiro
I didnt even know you can go bankrupt in this game. It didnt have a tooltip for further explanation. Thanks for clarifying.

I thought it would have made more sense if the businesses have such option (or even have longer notification) as I always end up with fewer businesses which kinda sucks.

If this is not a bug, it can be close now. Thank you.
