### ISSUE TITLE
Cannot use "flip conveyor" in orthographic camera view

### ISSUE THREAD

**Issue by sjdawson** [voxeltycoon/issues#699]
**Describe the bug**
In orthographic camera view, the flip conveyor tool won't highlight a conveyor to flip.

**Steps to reproduce**
- Enable orthographic camera
- Try using the flip conveyor tool, which won't highlight the conveyor

![xuiXcS5ye7](https://user-images.githubusercontent.com/1701603/117138322-c7017200-ada2-11eb-9e01-3f396deb9f3e.gif)

**Build version**
v0.85.1

**Platform**
Win 10, 20H2

**Reproducibility**
Every time

**Comment by sjdawson** [comment]
The new patch notes about orthographic view getting some love made me come and check in on this, it may not have been this patch, but it does appear to be fixed - I can now flip the conveyor in orthographic view. 👍🏻

**Comment by andrewpey** [comment]
Glad to hear it's finally resolved! Thanks for letting us know. We really appreciate it.
