### ISSUE TITLE
Game speed is 1x 4x 8x instead of 1x 2x 4x

### ISSUE THREAD

**Issue by tbjoern** [voxeltycoon/issues#708]
**Describe the bug**
In the controls menu, the game speeds are labelled as "1x", "2x" and "4x".
I measured how long each day takes in seconds using a stopwatch.
- 1x: 30s
- 2x: 7.5s
- 4x: 3.75s

The actual game speeds are 1x, 4x and 8x.

**Build version**
0.85.1.0 steam

**Platform**
Windows 10

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Fixed on the beta branch, thanks!
