### ISSUE TITLE
Trains behave abnormally - Unable to find way and stuck at signals

### ISSUE THREAD

**Issue by badlygoodguy** [voxeltycoon/issues#712]
**Describe the bug**
I have faced a series of issues with signals between two stations on one side of my map. 
Initially the 3 platform station was set to merge tracks a bit outside and then I noticed that the trains trying to choose 'any track' would literally come face to face at a signal and jam. I thought this was my lack of understanding of signals so I made them into two separate tracks running from their respective platforms on both the stations. I forgot to remove the signals and when I checked the trains were holding without moving on their own tracks.

In some cases one train would wait for the other train in its own separate track to enter the end station before it would move out. I gradually removed signals and tested the situation but it kept holding at successive signals and did not move, even though both trains were on separate tracks. They somehow waited for the other to enter and exit. By this time I had marked which platforms they could enter / exit on the stations so there was no reason for such confusion, especially when neither train had a way to switch tracks. 

I have taken multiple screenshots at various stages. Sharing them below.

![Signal issue 1](https://user-images.githubusercontent.com/15895762/117367084-4bf1a600-aedf-11eb-8b6b-1d54bda2435f.jpg)

![Signal issue 2](https://user-images.githubusercontent.com/15895762/117367359-b60a4b00-aedf-11eb-9860-ab3a74bd9cbf.jpg)

![Signal issue 3](https://user-images.githubusercontent.com/15895762/117367372-ba366880-aedf-11eb-8ebf-6d3063ffb7c8.jpg)

![Signal issue 4](https://user-images.githubusercontent.com/15895762/117367384-bdc9ef80-aedf-11eb-981a-214acd8ed225.jpg)

![Signal issue 5](https://user-images.githubusercontent.com/15895762/117367405-c3273a00-aedf-11eb-83db-d64cabe253b0.jpg)

![Signal issue 6](https://user-images.githubusercontent.com/15895762/117367412-c6bac100-aedf-11eb-9157-f0781dd3a523.jpg)

I cannot remember what all I tried in between but I tried bulldozing and rebuilding the end station (Popoli). I also saved the game, exited and then loaded it back over 12 hours later to see if this unexplained waiting is solved. All the signals in the screenshots are electric signals, the two tracks are two-ways and there are no pre-signals in the screen. 

The trains ran smoothly after removing all signals on tracks 1 and 2. My only thought here is that I mixed up something with the signalling initially but it should have run problem-free after the tracks and platforms were separated but they showed a holding behaviour for unconnected tracks.

The second problem I am having with the same set of tracks is that after I removed all signals on tracks 1 and 2, I wanted to deploy a train on Track 3 going across the currently explored map into another station. Initially the train refused to get out of the depot saying it sis not find a way to the station on the other side. 

I had set this particular train to go through the in between station without stopping and reach the station on the other side to pick up coal. Then return pass through the in-between station and reach Popoli. The train kept saying lost. After some finagling with the route, I set it to stop at the in-between station and wait. Then turn-around without picking up anything and come to Popoli.

This made the train come out of the depot as if it found the way and then it stopped midway again claiming to be lost. I then gave it turn around order to go to Popoli (nearest station to the depot). It went there but when I reset the route to go to the station on the other side from Popoli it said lost again. I made a bypass around the midway station and found that the train still claimed to be lost. I then snipped the connection to the midway station from the Popoli side and it is still claiming to be lost.

Attaching images of issue two showing the whole track I wish for the train 3 to go along.

![Train lost 0](https://user-images.githubusercontent.com/15895762/117370302-d4724580-aee3-11eb-829c-f3d8d7d2585d.jpg)

![Train lost 1](https://user-images.githubusercontent.com/15895762/117368492-3b422f80-aee1-11eb-93ee-7bba380b0ddd.jpg)

![Train lost 2](https://user-images.githubusercontent.com/15895762/117368503-4006e380-aee1-11eb-90a4-2aee091a226d.jpg)

![Train lost 3](https://user-images.githubusercontent.com/15895762/117368514-439a6a80-aee1-11eb-8682-37c0e6516a7d.jpg)

Point to note, I did not have any issue with trains on the first set of two stations I created on the other side. I used all signals on the track with merging and splitting. I had assigned specific platforms to the trains in that set. I ensured that my new train (Train 3 from Popoli) arrives on a free platform in the coal station where the other  two are operating.

I actually felt that I was understanding signalling part of the game correctly because of how smoothly that initial 2 trains worked out. 

**Steps to reproduce**
Build two stations of 3 platforms and 120 mtrs long.
Merge tracks outside stations to form one track.

Build a road tunnel under a mountain and lay track over tunnel to cross over the road since Arc bridge tech is the only one available at this early stage. In my case i could not get a Rail arc bridge over a road or a road arc bridge over a single rail. So I used the terrain rise to put a road tunnel and lay track over it.
Another rail tunnel was created by using the terraforming option to raise the level of a 'valley' in between two higher areas and then road was laid over rail track tunnel. This bit was to be used only by the last train which considered itself 'lost'.

After the merged tracks are laid, signal all track merging with 2 way electric signals. No pre-signals used. 
Initially let trains use any track.

Here I saw the first jam when the trains could have taken the other tracks to other platforms by following signals. I still assume human error here. Certain holding areas prior to merging may not have had enough length to contain the train and I can see how the jam could have happened.

After first jam, allocate platforms for trains. 

Here I saw smooth running until two trains going in the same direction on different tracks started holding for the other one to enter station before travelling on a block that should have declared clear a long while ago.

Then separate the two tracks, remove all merging, leave signals in original positions.

Now I notice holding for two trains on completely unconnected tracks.

Remove all signals, both trains run smoothly. 

Try to introduce train 3 on track 3 which was initially merging on to track 2 for a bit. The route requires passing through a station.

Train refuses to leave depot. Remove the merging on track 3 and fiddle with route to reduce route length and avoid passing through stations. Train leaves depot, tries to go to station but stops along track 3 and says 'I'm lost'.

Give turn around order, train goes to the other station. 

Reset the route to pass through midway station, train claims to be lost and does not move from station.

**Build version**
0.85.1.0 steam

**Platform**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2/‎14/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

**Reproducibility**
I will have to call it 'Often' but I have not reproduced this. I have only played 6 hours of the game in 2 maybe 3 sessions.
Save files attached.

**Logs/saves**
Save with 'holding' at signal on separate tracks issue - 
[Holding for signal on separate track.zip](https://github.com/voxeltycoon/issues/files/6437796/Holding.for.signal.on.separate.track.zip)

Save with 'Train lost' while sitting in the Depot
[Train lost in Depot.zip](https://github.com/voxeltycoon/issues/files/6437827/Train.lost.in.Depot.zip)

Save with 'Train lost' in the station
[Train lost at station.zip](https://github.com/voxeltycoon/issues/files/6437831/Train.lost.at.station.zip)

**Comment by DanielBarreleiro** [comment]
If I'm not wrong, these two pieces of railway are too close so get detected as being in the same block.
![image](https://user-images.githubusercontent.com/47695358/117372149-fc03e680-aec0-11eb-9a91-8568ac910545.png)

**Comment by badlygoodguy** [comment]
If so then I can check it by intentionally spacing them far apart. But the trains are running smoothly after i removed all signals. It there was a same block detection then maybe the trains would hold at stations. I am not sure.

Also this does not address issue with Train 3 being lost. I posted that along with this random holding because it is all in the same set of tracks.

**Comment by DBT85** [comment]
If there are no signals then there are no blocks. You don't need them for it to run, just to control things at junctions.

**Comment by badlygoodguy** [comment]
In case the tracks are too close together, I will sort it out in game as best as I can. It does feel counter-intuitive though.

I still need to know why Train 3 is lost.

**Comment by DanielBarreleiro** [comment]
> In case the tracks are too close together, I will sort it out in game as best as I can. It does feel counter-intuitive though.
> 
> I still need to know why Train 3 is lost.

I think i got it, there was a piece of track going down with a sharp edge.
![image](https://user-images.githubusercontent.com/47695358/117373196-ae887900-aec2-11eb-9fa5-a41836f11d6f.png)

**Comment by DanielBarreleiro** [comment]
It happens sometimes with roads too, I think it ahs been reported already.

**Comment by DBT85** [comment]
All should be fixed in the rework. I DL the files too but Dan got there first!

**Comment by badlygoodguy** [comment]
> I think i got it, there was a piece of track going down with a sharp edge.
> After deleting and placing again, it went on its business.

Ah! That is great to know, it has started working. Thanks for the help.

I do hope that the 'close tracks' thing get sorted out better.
