### ISSUE TITLE
.road assets ignore Hidden flag

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/issues#747]
**Describe the bug**
I have made a custom `.road` asset to be used in a custom `.roadstation` and it appears in the road construction UI despite having `"Hidden": true,`

**Steps to reproduce**
- Duplicate `regular.road` and name it `test.road`
- Change `Hidden` from `false` to `true`

**Build version**
0.86.0.0 steam
Issue was still present in older versions

**Platform**
Windows 10 (20H2, Build 19042.964)

**Reproducibility**
100%

**Logs/saves**
Here's a sample `.road` file to be placed in `Content` to test:
[Road not hidden.zip](https://github.com/voxeltycoon/issues/files/6467493/Road.not.hidden.zip)

**Comment by andrewpey** [comment]
The fix is live on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
