### ISSUE TITLE
replacing a train doesn't pay you for the old train

### ISSUE THREAD

**Issue by ZnCsdad** [voxeltycoon/issues#800]
**Describe the bug**
as the title suggests if you sell the train parts you get paid for the train... but if you replace the train you get charged for the new train but aren't refunded any money for the old one.

**Comment by ElvisCooper0815** [comment]
The refund is calculated in the price which you pay for the new vehicle. You can check the prices and see that you pay less than the price is shown in the Vehicle selection.
