### ISSUE TITLE
Home Screen/Starting Glitch

### ISSUE THREAD

**Issue by Kenny8908255** [voxeltycoon/issues#806]
I am running Voxel Tycoon on my Mac, sometimes when starting the game, it takes awhile for things to load normally (for example the different menus on the home page darkening when hovered over). The Home Screen can also glitch wildly where the entire screen glitches and I can still click on things but the flashing frames continue. I have quit the game and restarted it and it has happened nearly every time for me.

**Comment by andrewpey** [comment]
From the description, it sounds like a graphical driver issue. Feel free to comment if the issue is still happening.
