### ISSUE TITLE
Doesn't launch on mac

### ISSUE THREAD

**Issue by Ciuitas** [voxeltycoon/issues#814]
**Describe the bug**
Loading the game for a few minutes with dark blue screen then crashes. Gatekeeper disabled. I launched games with higher requirements that actually worked. But VoxelTycoon doesn't:(
I will try on Bootcamp later. Maybe it'll work on Windows

**Steps to reproduce**
Launch from steam

**Build version**
Big Sur 11.3.1
2.9GHz dual-core Intel Core i5
8GB of 2133MHz LPDDR3
Intel Iris Graphics 550

**Platform**
MacOS

**Reproducibility**
Everytime, hasn't played the game yet

**Logs/saves**
Couldn't find any logs

**Comment by andrewpey** [comment]
Sorry for being this late. Did you manage to run the game?

**Comment by Ciuitas** [comment]
Hi,
It launched, I can't remember how I did that though

пт, 12 нояб. 2021 г., 21:05 Andrey Peysakhovich ***@***.***>:

**Comment by andrewpey** [comment]
Good to know!
