### ISSUE TITLE
Access to resource blocked in early game

### ISSUE THREAD

**Issue by Ch3w84cc4** [voxeltycoon/issues#824]
**Describe the bug**
I have had a number of new games where there is a resource near water. As the adjourning areas are locked, I can't build around the water to connect the resource and it is a key element to building up the cash flow.
**Steps to reproduce**
Start a new game and look for resource locked by water

**Build version**
V0.86

**Platform**
Windows 10 Ultimate

**Reproducibility**
Often

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/issues/discussions/650) if applicable.

**Comment by DanielBarreleiro** [comment]
I hope I'm understanding this correctly..
Have you tried building a bridge over the water?

**Comment by Ch3w84cc4** [comment]
Hi Daniel, thank you for your quick response. Apologies it is user error on my part. I was expecting a bridge to automatically build across the water and then subsequently saw that there is an option to build a bridge below where it said road, so please close the defect as it is down to user error.

**Comment by DanielBarreleiro** [comment]
@Ch3w84cc4 I'm not a collaborator so I can't close it, I think you should have an option to close it tho?
If not, dont worry, one of the collaborators probably will when they see it.
