### ISSUE TITLE
Wrong slope force calculation for flipped vehicles

### ISSUE THREAD

**Issue by xmnovotny** [voxeltycoon/issues#890]
When vehicle is flipped, slope force (and acceleration/power needed) is calculated as on opposite direction - going downhill will slow down the vehicle and vice versa.

**Steps to reproduce**
Build long slope, long doubleheaded train and observe speed, acceleration and power needed for going uphill and downhill after whole train reverse its direction.

**Build version**
0.86.1.0

**Platform**
Windows 10

**Reproducibility**
Everytime

**Fix**
In function Vehicle.GetSlopeForce multiply whole result by -1 when Vehicle.IsFlipped and subresults by -1 when VehicleUnit.IsFlipped

**Comment by andrewpey** [comment]
Thanks, will be fixed with `0.87`.

**Comment by andrewpey** [comment]
The fix is live on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
