### ISSUE TITLE
easy money multiplication by changing the currency setting ingame.

### ISSUE THREAD

**Issue by agawa98** [voxeltycoon/issues#891]
**Describe the bug**
You can easily multiply your money

**Steps to reproduce**
i was fiddling around with currency setting, and when i changed dollars (my default) to polish zloty (PLN), and then to russian rubels (RUB), and when i changed it back to dollars USD, my money got multiplied by around 35 times or so (before changing cureency i had around 1.3millon usd, after - around 38mil). I think it happened between PLN and RUB but im not sure.

**Build version**
0.85.0.24

**Platform**
Windows 10 64bit version 1909

**Reproducibility**
How often an issue reproduces: every time you change the currency

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/issues/discussions/650) if applicable.

**Comment by andrewpey** [comment]
We are not able to reproduce the issue. However, if you switch to `$(ARS)` instead of `$(USD)` by mistake, you can see that your money is multiplied. We believe that was the case.
