### ISSUE TITLE
Game can't be restarted after a crash occured

### ISSUE THREAD

**Issue by Livedeath2k** [voxeltycoon/issues#892]
**Describe the bug**
While I played that game the game crashed unpurposedly back to desktop.
I tried then to restart the game a new but Steam didn't recognized that the game stopped running and signaled me that the game is already running.
If i try to start the game manually via exe the game stopped working after several seconds and Steam shows me the error That the game can't be updated while its running already.

Please check also why the crash handler didn't catch the crash. My game was modded so i expect a mod that produces the crash. But the crash handler didn't jump in after the game crashed to log everything.

**Steps to reproduce**
Crash your game to desktop and try to restart it.

**Build version**
Actual available Steam version.

**Platform**
Windows 10 64bit.

**Reproducibility**
every time

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/issues/files/7072412/Player.log)

**Comment by andrewpey** [comment]
If Steam continue to show the game as running, it means that the exe haven't closed for some reason, even if it doesn't have any window opened. That means that the error somehow broke the renderer/window but didn't crashed the executable completely.

Unfortunately, the attached log file is from the post crash run (via exe). We need the log just after the problem occured to investigate the issue. Closing now, feel free to comment if this will happen again.
