### ISSUE TITLE
three seperate railways, one signal block

### ISSUE THREAD

**Issue by dumbbumb228** [voxeltycoon/issues#896]
**Describe the bug**
three completely separate signal blocks count as the one and works as the one. three different railways 1 signal block, 
![20210906204543_1](https://user-images.githubusercontent.com/90213240/132250578-6455998e-45a8-4583-a9ab-4a1d24a52a54.jpg)

**Steps to reproduce**
that just happened

**Build version**
0.86.1.0 Steam

**Platform**
Windows 8.1

**Reproducibility**
happened and can't  be fixed

**Logs/saves**
[f6yytisza26.zip](https://github.com/voxeltycoon/issues/files/7117381/f6yytisza26.zip)

**Comment by DanielBarreleiro** [comment]
Which block are you talking about?
This one?
![image](https://user-images.githubusercontent.com/47695358/132253681-8df57dcc-eb7f-4f8e-9290-7586fda54b50.png)
The tracks are too close on that turn, this has been pointed out many times.
Train will crash if there's another train on the other side.

**Comment by dumbbumb228** [comment]
i suspected this, so i tried to move it away or break it down completely. Nothing changed

**Comment by dumbbumb228** [comment]
> Which block are you talking about?
> This one?
> ![image](https://user-images.githubusercontent.com/47695358/132253681-8df57dcc-eb7f-4f8e-9290-7586fda54b50.png)
> The tracks are too close on that turn, this has been pointed out many times.
> Train will crash if there's another train on the other side.

i suspected this, so i tried to move it away or break it down completely. Nothing changed

**Comment by DanielBarreleiro** [comment]
> > Which block are you talking about?
> > This one?
> > ![image](https://user-images.githubusercontent.com/47695358/132253681-8df57dcc-eb7f-4f8e-9290-7586fda54b50.png)
> > The tracks are too close on that turn, this has been pointed out many times.
> > Train will crash if there's another train on the other side.
> 
> i suspected this, so i tried to move it away or break it down completely. Nothing changed

Here, like I said, move it a bit further away.
![image](https://user-images.githubusercontent.com/47695358/132394856-f915772b-999d-439d-a8a5-6f222180827d.png)

**Comment by victorleblais** [comment]
As Daniel pointed out, the problem was that the tracks are too close for trains to cross each others

**Comment by Roanmh** [comment]
Hi, sorry to drag up a closed issue. I just want to mention that the same thing happened to me.

It's not obvious that trains would crash in this situation, which makes it very hard to see why the blocks are combined. I wonder if a UI improvement could make this situation (and the resolution) more obvious. Thanks!

**Comment by dumbbumb228** [comment]
> Hi, sorry to drag up a closed issue. I just want to mention that the same thing happened to me.
> 
> It's not obvious that trains would crash in this situation, which makes it very hard to see why the blocks are combined. I wonder if a UI improvement could make this situation (and the resolution) more obvious. Thanks!

i agree
