### ISSUE TITLE
Vehicle replacement bypasses tech requirements

### ISSUE THREAD

**Issue by emerging-tub** [voxeltycoon/issues#921]
Vehicles under 'Diesel Engine 1' require garage level 2 to deploy. However, In beta branch, the 'vehicle replacement' feature allows this requirement to be entirely bypassed

complete diesel engine 1 research
do NOT complete roads 2 research (unlocks garage 2 - requirement for deploying diesel vehicles)
start a new vehicle replacement order to replace current vehicles with diesel
garage 2/roads 2 requirement has been bypassed

**Build version**
0.87.0.6 steam

**Platform**
Win 10 home
Vers 21H1
Build 19043.1415

**Reproducibility**
reproduces: every time

**Logs/saves**
N/A

**Comment by andrewpey** [comment]
You closed the issue, so this is not the case?

**Comment by emerging-tub** [comment]
Hello,
That is correct, it had been the case a few days ago and I had submitted
the ticket before checking again today. Now when diesel vehicle
replacements are scheduled, if there are no level two garages, the user is
prompted "no suitable garage available" or something along those lines.
