### ISSUE TITLE
Clicking on a train depot has no action. It throws exception.

### ISSUE THREAD

**Issue by nestorpan** [voxeltycoon/issues#922]
**Describe the bug**
Clicking on a train depot has no action.

**Steps to reproduce**
Build a train depot. Buy a train on that depot. Click the depot.

**Build version**
0.87

**Platform**
Windows 11

**Reproducibility**
Every time.

**Logs/saves**
Log attached.
It does not allow me to attach save file.

[Player.log](https://github.com/voxeltycoon/issues/files/7768932/Player.log)

Thanks!
Néstor

**Comment by andrewpey** [comment]
Looks like the [Game Control](https://steamcommunity.com/sharedfiles/filedetails/?id=2463082972) mod is not yet updated for 0.87. You can reach the author to ask them to update it.

In the meantime, you can disable the mod in your save game.

To disable a mod: Load game -> three dots in the top right corner of the save card -> Add or remove mods.
