### ISSUE TITLE
Train-Window didnt appear

### ISSUE THREAD

**Issue by kxonix** [voxeltycoon/issues#923]
[Player.log](https://github.com/voxeltycoon/issues/files/7770381/Player.log)
Since last Update, but also in beta, the train-window didnt appear anymore. So i cant reconfigure trains or send them to depots or whatever. Vehicle-Window appears.

**Comment by DanielBarreleiro** [comment]
This topic is also on the steam forums:
https://steamcommunity.com/app/732050/discussions/1/3202619099972214027/

> My savegame is now playable, i found out that the combination of the mods "better vehicle capacity display", "floor tool" and "game control" cause the error that click on buying new trains didnt work and clicking on trains not working.

May be related to the same as 922.

**Comment by andrewpey** [comment]
[Was caused by mods](https://steamcommunity.com/app/732050/discussions/1/3202619099972214027/).
