### ISSUE TITLE
close parallel diagonal tracks act as one circuit for signaling

### ISSUE THREAD

**Issue by jackfruh** [voxeltycoon/issues#931]
**Describe the bug**
two tracks, too close together, are picked up as the same track segment for signaling. 
This means a train traveling on either track segment blocks trains from the other segment.

**Steps to reproduce**
Two tracks mainline, with an "S" curve that requires diagonals, make the sections of track on the diagonal closer together (but not touching)

**Build version**
0.87.0.6 steam

**Platform**
windows 10 x64

**Reproducibility**
every time

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/issues/discussions/650) if applicable.

**Comment by PrathamKalgutkar** [comment]
While I'm not a developer or understand the game engine, all I know by far is that this behaviour to treat such tracks as single block is intended and implemented(?) to avoid train collision

**Comment by andrewpey** [comment]
Duplicate of https://github.com/voxeltycoon/issues/discussions/775.
