### ISSUE TITLE
Option to disable chromatic aberration

### ISSUE THREAD

**Issue by BloodyRain2k** [voxeltycoon/issues#932]
**Describe the bug**
I'm glad that the current strength of this effect isn't strong, it's actually very faint (green/red phasing in the screen corners).
But I would still like to ask for a setting to turn it off, because it might cause me a headache in longer sessions.

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
0.87.0.6 Steam

**Platform**
Win 7 x64

Example: the magenta / green phasing that occurs near the screen edges.
![Desktop Screenshot 2022 01 01 - 15 57 39 73](https://user-images.githubusercontent.com/1014362/147853465-d4a30956-1f2c-45b1-9b06-3f44c62d1010.png)

**Comment by andrewpey** [comment]
We've added an option to disable this and other camera effects in [0.87.1](https://voxeltycoon.xyz/changelog#0.87.1) (check _Settings / Video tab / Camera effects_ at the bottom).
