### ISSUE TITLE
Can configure vehicle replacement before suitable depots exist (or have been researched) - AND you can this use "clone" to get those vehicles

### ISSUE THREAD

**Issue by trauts** [voxeltycoon/issues#936]
**Describe the bug**
You can create replacements that cannot be fulfilled, which fills notifications with "cannot find route to suitable depot"  - and the replacement cannot be cancelled so you get endless messages until you build a suitable depot.

*Once you have created this replacement, though, you can use clone to get the new (unavailable) vehicle class*

Bug 1: you should not be able to set up a replacement for vehicles that you do not have a depot for
Bug 2: "clone" of a vehicle that is in a replacement program should only provide the replacement vehicle if legal for the given depots

**Steps to reproduce**
Bug 1:
* Research Diesel Engine, but not Roads II, so you have availability of Diesel vehicles but no ability to buy them (no suitable garages)
* Configure a replacement for a petrol vehicle with its replacement diesel
* Get messages for each and every vehicle
Bug 2:
* Open a "Garage 1" depot view
* Use "Clone" for on any vehicle that is in the impossible replacement program - it appears (even if incompatible with depot).

**Build version**
0.87

**Platform**
Windows 11

**Reproducibility**
Unclear

**Logs/saves**
[save file 69700e2gq9e.zip](https://github.com/voxeltycoon/issues/files/7799636/69700e2gq9e.zip)
_you will have to pause immediately on opening as ROADS II research is nearly complete_

**Comment by andrewpey** [comment]
Should be fixed on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
