### ISSUE TITLE
Settings toggles not switching

### ISSUE THREAD

**Issue by DanielBarreleiro** [voxeltycoon/issues#950]
**Describe the bug**
When opening the settings page inside a game (it works fine on main menu), the toggles don't switch colours neither do the toggling animation. They still toggle and work, switching settings tab and go back updates the UI and shows the toggle switched.
![image](https://user-images.githubusercontent.com/47695358/153930684-c4f91f08-f308-460e-82ed-053565d7f883.png)

https://user-images.githubusercontent.com/47695358/153931820-ff379ae5-d0e9-409e-8e94-c2a45b396863.mp4

**Steps to reproduce**
Open settings page inside a game and try switching the toggles.

**Build version**
0.87.1.3 steam

**Platform**
Linux Native - Debian 12

**Reproducibility**
Every time

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/issues/files/8063363/Player.log)

**Comment by andrewpey** [comment]
Thanks for reporting this, we'll fix it with the next update 👍

**Comment by andrewpey** [comment]
Fix is live on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
