### ISSUE TITLE
Fat Passengers

### ISSUE THREAD

**Issue by mykael22000** [voxeltycoon/issues#952]
**Describe the bug**
Looking at the details panel for my bus, each passenger weighs 1t.

**Steps to reproduce**
Set up a bus circuit and watch the vehicle weight in the Bus Details as passengers get on and off.  3t bus plus 10 passengers = 13t total weight.  Should probably be around the 150kg figure airlines use.

**Build version**
0.87.0.6 steam

**Platform**
Windows 10

**Reproducibility**
Constant.

**Logs/saves**
N/A

**Comment by andrewpey** [comment]
Fixed on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
