### ISSUE TITLE
Linux Fedora. Can't use "R" button for rotate any buildings

### ISSUE THREAD

**Issue by juandeart** [voxeltycoon/issues#975]
**Describe the bug**
I can't built bridges or tunnel by T and B button. And can't rotate any buildings by R buttons

**Steps to reproduce**
I'm sorry I don't know how reproduce this issue. I just ran the game after pause and discover this problem

**Build version**
v.0.87.1

**Platform**
Linux Fedora 36
**Reproducibility**
every time, even I start new game.
[Player.log](https://github.com/voxeltycoon/issues/files/9149686/Player.log)

**Comment by andrewpey** [comment]
Is the issue still present?

**Comment by juandeart** [comment]
> 

yes

**Comment by andrewpey** [comment]
Can I ask you to try to uninstall the game and then install it again?

**Comment by juandeart** [comment]
I've done it but rotate at the same not working

**Comment by andrewpey** [comment]
Does other typing working (like naming a file when you save a game?).

Can I see a screenshot of controls tab from the in-game settings?

**Comment by juandeart** [comment]
Hi! My apologize for long response. I've just change all buttons for another, and now everything is working

**Comment by andrewpey** [comment]
Thanks for getting back! We can close this then.
