### ISSUE TITLE
Game always crashes in full screen after spending 5-10 seconds in the starting screen

### ISSUE THREAD

**Issue by GitchalWoo** [voxeltycoon/issues#980]
**Describe the bug**
Everytime that I turn on the game on fullscreen, the game crashes. It works fine in window mode. I do not have any other problems with other unity based games. Basically the whole driver crashes and stalls the computer without even a event log updated or player log information. Basically the whole computer gets into a halt without logging the issue.

**Steps to reproduce**
Turn on the game and wait in menu for some time in fullscreen.

**Build version**
v.0.87.1

**Platform**
Windows 11 Insider Preview on AMD with newest drivers
[DxDiag.txt](https://github.com/voxeltycoon/issues/files/9388591/DxDiag.txt)

**Reproducibility**
Every time

**Logs/saves**
It happens in the menu and does not leave traces of logs - nor in game logs nor in

**Comment by GitchalWoo** [comment]
The problem does not appear afte recent patches

**Comment by andrewpey** [comment]
Thank you for getting back to us and letting us know.
