### ISSUE TITLE
Vehicle stats are no longer displayed when hovering over a vehicle preview in the tech tree window

### ISSUE THREAD

**Issue by Matschkopf** [voxeltycoon/issues#982]
Hello developers, I use the beta branch with the latest version. 0.87.2.0 steam
In the research tree a wrong display is shown in the preview.

Before this version there were always short infos e.g. of vehicles to see. Now an info appears that actually belongs in the garage.
If you click on it, the display disappears completely. 

![20220903145409_1](https://user-images.githubusercontent.com/96974727/188308902-2620c466-60c1-4591-aa69-bc5f194b11a9.jpg)
![20220903145412_1](https://user-images.githubusercontent.com/96974727/188308903-e1b42fc5-c303-40c4-8161-1de0a2732318.jpg)

**Comment by andrewpey** [comment]
Fix available on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
