### ISSUE TITLE
The cargo platform was destroyed

### ISSUE THREAD

**Issue by isPoto** [voxeltycoon/issues#983]
**Describe the bug**
Stations are always destroyed and the error at the top of the screen prompts causes.

When I click on a destroyed building, its building window shows that your building has been destroyed and then a red banner appears at the top of the screen warning you that an error has occurred. Then I can't close the destroyed building window, and I can feel a significant drop in responsiveness. And it still says your building is destroyed even if I delete it and rebuild it. No longer able to play properly

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/59009389/188719608-52d3ab87-5ade-4976-807a-b7ca31594177.png)
![image](https://user-images.githubusercontent.com/59009389/188733687-85d10f52-4bf7-4bb0-8560-1207e00461a9.png)
![image](https://user-images.githubusercontent.com/59009389/188733746-20e0bcb5-a7ec-4586-9431-bc786799127f.png)

**Build version**
v0.87.2.0

**Platform**
Win10 21H1

**Reproducibility**
often

**Logs/saves**
ArgumentException: At least one object must implement IComparable.
System.Collections.Comparer.Compare (System.Object a, System.Object b) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.ObjectComparer`1[T].Compare (T x, T y) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Linq.EnumerableSorter`2[TElement,TKey].CompareAnyKeys (System.Int32 index1, System.Int32 index2) (at <523a924aba464755b1747653b71e5189>:0)
System.Linq.EnumerableSorter`2[TElement,TKey].CompareAnyKeys (System.Int32 index1, System.Int32 index2) (at <523a924aba464755b1747653b71e5189>:0)
System.Collections.Generic.ComparisonComparer`1[T].Compare (T x, T y) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.ArraySortHelper`1[T].SwapIfGreater (T[] keys, System.Comparison`1[T] comparer, System.Int32 a, System.Int32 b) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.ArraySortHelper`1[T].IntroSort (T[] keys, System.Int32 lo, System.Int32 hi, System.Int32 depthLimit, System.Comparison`1[T] comparer) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.ArraySortHelper`1[T].IntrospectiveSort (T[] keys, System.Int32 left, System.Int32 length, System.Comparison`1[T] comparer) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.ArraySortHelper`1[T].Sort (T[] keys, System.Int32 index, System.Int32 length, System.Collections.Generic.IComparer`1[T] comparer) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
Rethrow as InvalidOperationException: Failed to compare two elements in the array.
System.Collections.Generic.ArraySortHelper`1[T].Sort (T[] keys, System.Int32 index, System.Int32 length, System.Collections.Generic.IComparer`1[T] comparer) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Array.Sort[T] (T[] array, System.Int32 index, System.Int32 length, System.Collections.Generic.IComparer`1[T] comparer) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Linq.EnumerableSorter`2[TElement,TKey].QuickSort (System.Int32[] keys, System.Int32 lo, System.Int32 hi) (at <523a924aba464755b1747653b71e5189>:0)
System.Linq.EnumerableSorter`1[TElement].Sort (TElement[] elements, System.Int32 count) (at <523a924aba464755b1747653b71e5189>:0)
System.Linq.OrderedEnumerable`1[TElement].SortedMap (System.Linq.Buffer`1[TElement] buffer) (at <523a924aba464755b1747653b71e5189>:0)
System.Linq.OrderedEnumerable`1[TElement].ToList () (at <523a924aba464755b1747653b71e5189>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <523a924aba464755b1747653b71e5189>:0)
VoxelTycoon.Game.UI.StorageNetworking.StorageNetworkTabHelper.InvalidateSourcesAndTargets (VoxelTycoon.IStorageNetworkNode currentNode, System.Collections.Generic.List`1[T] sourceNodes, System.Collections.Generic.List`1[T] targetNodes, UnityEngine.Transform sourcesContainer, UnityEngine.Transform sourcesItemsContainer, UnityEngine.Transform targetsContainer, UnityEngine.Transform targetsItemsContainer) (at <ac24a7b174d74b3f8e62d65ebc745689>:0)
VoxelTycoon.Game.UI.StationWindowOverviewTab.InvalidateSourcesAndTargets () (at <ac24a7b174d74b3f8e62d65ebc745689>:0)
VoxelTycoon.Game.UI.StationWindowOverviewTab.Update () (at <ac24a7b174d74b3f8e62d65ebc745689>:0)

**Comment by andrewpey** [comment]
Can I ask you to share a save file with a broken station please?

**Comment by isPoto** [comment]
> Can I ask you to share a save file with a broken station please?

How do I find this file?

**Comment by andrewpey** [comment]
@isPoto Load game -> Tree dots in the top right corner -> Share.
![image](https://user-images.githubusercontent.com/1748681/188838734-0715bbd6-2a5a-4e85-8205-b42a54b416f9.png)

**Comment by andrewpey** [comment]
Nvm, we've located the issue, will be fixed with the next beta update, thank you.

**Comment by andrewpey** [comment]
Fix available on the [beta branch](https://voxeltycoon.xyz/devlog/beta-branch/).
